### ISSUE TITLE
parallel multiple progress bars possible ?

### ISSUE THREAD

**Issue by salimane** [piotrmurach/tty-progressbar#1]
I would like to ask if it's possible with `tty-progressbar` to display multiple progress bars at the same time from multiple processes. For example, something like : 

```
downloading file1 [=======================       ]
downloading file2 [======                        ]
downloading file3 [=============                 ]
downloading file4 [==========                    ]
```

Thanks

**Comment by kke** [comment]
[![asciicast](https://asciinema.org/a/b086kx1b0mq85yukxaltgchjt.png)](https://asciinema.org/a/b086kx1b0mq85yukxaltgchjt)

```ruby
require 'tty-progressbar'
require 'tty-cursor'

subtasks = ['footask', 'bartask', 'baztask', 'dogtask', 'cattask']

puts "\n" * (subtasks.size + 1) # make room for the bars

main_bar = TTY::ProgressBar.new(" maintask [:bar] :percent", total: subtasks.size * 50)
sub_bars = subtasks.map { |st| TTY::ProgressBar.new("  #{st} [:bar] :percent", total: 50) }
until main_bar.complete?
  print TTY::Cursor.up(subtasks.size)
  main_bar.current = sub_bars.map(&:current).inject(:+)
  sub_bars.each do |bar|
    print TTY::Cursor.next_line
    unless bar.complete?
      bar.advance(rand(5))
      print TTY::Cursor.prev_line if bar.complete?
    end
  end
  sleep 0.1
end
```

**Comment by kke** [comment]
Maybe it could accept `:row` as option and it would move to row X before `write`.

**Comment by piotrmurach** [comment]
That's a sweet demo! I'm convinced that we can add multi bar support. I think this would ideally be another class that acts as a container for the progressbar definitions and stores the total progress.

```ruby
# create multi bar container that will hold total progress and render all the bars
multi_bar = TTY::ProgressBar::Multi.new 

# create the bars configurations relying on TTY::ProgressBar configuration
bar1 = multi_bar.create("[:bar] :percent", total: 50)
bar2 = multi_bar.create("[:bar] :percent", total: 20)
bar3 = multi_bar.create("[:bar] :percent", total: 30)

multi_bar << bar1
multi_bar << bar2
multi_bar << bar3

# run the bars by progressing
until multi_bar.complete?
  multi_bar.advance(1, rand(5)) # advance bar 1 by value
  multi_bar.advance(2, rand(5))
  multi_bar.advance(3, rand(5))
end
```

or we can maybe do something more event driven when any of the bars progress they will notify multi bar.

```ruby
# each time any of the bars changes it would notify multibar
multi_bar.start_listening

Thread.new do
  1.upto(50) { |i| bar1.advance(i) }
end

Thread.new do 
  1.upto(20) { |i| bar2.advance(i) }
end
```

Any thoughts?

**Comment by kke** [comment]
Evented would be awesome. And then write a trackable puts to allow printing and scrolling and soon we have ncurses.  

Also tty-sparklines or such for drawing graphs or bar charts.

Future sounds sweet.

**Comment by piotrmurach** [comment]
Do you want to take a stab at implementing the evented version? I kind of feel as though it would be better to start with the simpler version and layer eventing on top of it. As much as I would like to get it done I have quite few open source things to tackle first.

I have written original idea for `tty-*` packages in 2012 on a piece of paper and I still have it. I have so far managed to cross out about half of the libraries that I wanted to write originally. There is still plenty of good stuff to come!

**Comment by kke** [comment]
Thinking about it.

If the bars know their coordinates it should be pretty simple from there on.

**Comment by piotrmurach** [comment]
@kke @salimane  This is implemented in master and works with threads - try [multi bar example](https://github.com/piotrmurach/tty-progressbar/blob/master/examples/multi/main_bar.rb)

**Comment by salimane** [comment]
awesome @piotrmurach thank you very much 🍾

**Comment by piotrmurach** [comment]
@salimane it only took over 2 years to implement and close the very first issue 😄
