### ISSUE TITLE
Thank you for tty-progressbar

### ISSUE THREAD

**Issue by janko-m** [piotrmurach/tty-progressbar#17]
Hey Piotr!

I just wanted to thank you for creating tty-progressbar! It really helped us in a complex database migration that we had at work recently, it was so incredibly convenient to have all of these features available:

* ETA display
* rate display
* logging
* `frequency` option
* `interval` option

Just wanted to let you know that it worked great for us, and thank you for all your awesome work! ❤️

**Comment by piotrmurach** [comment]
Hey Janko! Thanks for the feedback :heart: I'm really happy that tty-progressbar worked for you so well. There wouldn't be much sense in crafting tty tools if people didn't find them handy in their everyday scripts.
