### ISSUE TITLE
thread safe?

### ISSUE THREAD

**Issue by jrochkind** [piotrmurach/tty-progressbar#21]
Is a TTY:Progressbar threadsafe, can I share an instance between multiple threads, all of which call `advance` on it?

**Comment by piotrmurach** [comment]
Hi Jonathan,

Currently `tty-progressbar` is not threadsafe. Having said that, I'm planning to add multibar support which will require it to be multi threaded. Do you fancy submitting support for multithreading? I keep the source fairly minimal and well documented.

**Comment by jrochkind** [comment]
Hmm, could be tricky to make thread-safe while retaining performance. I'm not quite sure how to approach it, and probably don't have time to. 

For my needs, I'd probably just protect access to `progressbar.advance`  in a mutex in my own dependent code, and have my individual threads only call `advance` every X number of actual advances to try and avoid too much contention for the mutex.

**Comment by piotrmurach** [comment]
I've added threads support for advancing bar. In terms of performance, I'm aware this slows things down a bit but given that I want to provide a multi progressbar support this is a fine compromise. To reduce contention you can use `:frequency` option to throttle painting.

**Comment by jrochkind** [comment]
That sounds perfect, thanks. I was actually recently wanting a way to throttle painting even _without_ concurrency, I was using progressbar for something that updated very frequently, and I thought the painting or progressbar might actually be slowing down the task. So awesome, thanks!
