### ISSUE TITLE
Be aware of Unicode width

### ISSUE THREAD

**Issue by msg7086** [piotrmurach/tty-progressbar#26]
Progress Bar sometimes can have Unicode characters, such as CJKs from a file name.

Consider computing unicode width instead of string length, if `unicode-display_width` gem is loaded.

(Or use other equivalent strategies.)

**Comment by piotrmurach** [comment]
Very good point! I use `unicode-display_width` in couple of my gems. I would like to figure out an unobtrusive way to add unicode length support without forcing everyone to download this gem.

**Comment by piotrmurach** [comment]
I have implemented support for rendering unicode characters correctly given the bar width. Please see [unicode docs](https://github.com/piotrmurach/tty-progressbar#44-unicode) for more information. I will release shortly.

**Comment by piotrmurach** [comment]
Released `v0.15.0` that fixes Unicode issues.
