### ISSUE TITLE
`log` feature ala ruby-progressbar

### ISSUE THREAD

**Issue by jrochkind** [piotrmurach/tty-progressbar#34]
Sometimes while a progress bar is in progress, you want to output some status or log information. 

ruby-progressbar has a `log` feature that will let you print some lines to the screen , without completely messing up the painting of the still-in-progress progress bar. https://github.com/jfelchner/ruby-progressbar/wiki/Logging

tty-progressbar appears not to have this feature? It's a crucial one. 

Came up on on a /r/ruby question. https://www.reddit.com/r/ruby/comments/9nhos9/suggest_a_pretty_command_line_program_toolkit/

**Comment by piotrmurach** [comment]
hmmm....[logging](https://github.com/piotrmurach/tty-progressbar#5-logging) section.... 😉

**Comment by piotrmurach** [comment]
@jrochkind Thanks for letting me know about the thread, I've added my 5 cents...
