### ISSUE TITLE
Time left indication

### ISSUE THREAD

**Issue by obromios** [piotrmurach/tty-progressbar#44]
### New feature request
This is a very useful gem.  Have you considered adding the facility to provide a 'time left' indicator?

It should be possible to track the rate of progress of the bar,  test if it is approximately linear, and if so, provide on ongoing indicator of the actual time left?   You could also try to fit models other than linear.

Although it may take some time for me to get around to it, I would be prepared to prototype such a feature.

**Comment by piotrmurach** [comment]
Hi Chris! 👋 

Thanks for using `tty-progressbar`.

Have you seen the `:eta` token? There are other [tokens available](https://github.com/piotrmurach/tty-progressbar#41-tokens).

**Comment by obromios** [comment]
That is perfect. I also find the other members of the tty family useful. Great library, thank you.
