### ISSUE TITLE
strings-ansi gem version conflict with other latest tty gems

### ISSUE THREAD

**Issue by AndyObtiva** [piotrmurach/tty-progressbar#45]
### Are you in the right place?
* For issues or feature requests file a GitHub issue in this repository
* For general questions or discussion post in [Gitter](https://gitter.im/piotrmurach/tty)

### Describe the problem
A brief description of the issue/feature.

Hi, I tried using tty-progressbar in a [project of mine](https://github.com/AndyObtiva/bundler-download) and mix it with [another project](https://github.com/AndyObtiva/glimmer-dsl-swt) using the latest versions of tty-markdown and tty-prompt, and a gem conflict occurred that forced me to downgrade them to accommodate strings-ansi '~> 0.1.0' (from 0.2)

I just saw you have changed the dependency to `~> 0.2', which would resolve my issue.

My only question is when will you be making the next release? And, if not soon, would you be able to make a quick patch release in the meantime with only that dependency change?

### Describe your environment

* OS version: Mac Catalina
* Ruby version: Ruby 2.7.1 and JRuby 9.2.13.0
* TTY::ProgressBar version: 0.17.0

**Comment by piotrmurach** [comment]
Thanks for posting this issue. I'm aware of this and it's on my list. The two remaining `tty` gems that need upgrading is this one and `tty-command`. I'm waiting for a feature review of the indeterminate progress and plan to release a new version this coming weekend.

**Comment by dkowis** [comment]
I just hit this again, can't use `tty-table` and this at the same time :(

**Comment by piotrmurach** [comment]
@dkowis There will be a release soon. The `tty-progressbar` is the last remaining gem from `tty` to update but I need to get the API right. The indeterminate progress feature is in, I just added `:bar_format` for choosing preconfigured bar displays. The last thing that remains to do is to get pausing/resuming behaviour for multi bars working https://github.com/piotrmurach/tty-progressbar/issues/37. All the `tty` gems took few months to update but going forward the process will be much smoother.

**Comment by piotrmurach** [comment]
Released `v0.18.0`. Definitely the biggest release so far. This version is feature-packed, see [changelog](https://github.com/piotrmurach/tty-progressbar/blob/master/CHANGELOG.md). Enjoy!
