### ISSUE TITLE
ETA on a new release?

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-progressbar#47]
I see a few nice things like the `bar_format` option that has not yet made its way to a release + I noticed the latest release is from over a year ago.

Would love to have a new version published soon.

**Comment by piotrmurach** [comment]
Thanks for the issue. There are many goodies in this release including indeterminate progress. Sorry for the late reply, so many things to maintain and so little time. I'm currently wrapping up `tty-reader` release and after that, I'll switch my focus to this gem. The https://github.com/piotrmurach/tty-progressbar/issues/45 issue is also asking for a new release. Be assured I'll work on this as I want to release a new `tty` this month which is dependent on this gem. I still need to tighten up the `pause` and `resume` behaviour.

**Comment by piotrmurach** [comment]
Released `v0.18.0`. Probably the biggest release for this gem so far. It's feature-packed, see [changelog](https://github.com/piotrmurach/tty-progressbar/blob/master/CHANGELOG.md) for details. Enjoy!

**Comment by DannyBen** [comment]
Thank you!
