### ISSUE TITLE
Indeterminate MultiBars raise `undefined method `+' for nil:NilClass`

### ISSUE THREAD

**Issue by ttilberg** [piotrmurach/tty-progressbar#49]
### Describe the problem
Upon multibar registration, the parent's total is recalculated. This raises:

```
NoMethodError: undefined method `+' for nil:NilClass
```

I'll submit a PR to fix.

### Steps to reproduce the problem

```rb
require 'tty/progressbar/multi'

main = TTY::ProgressBar::Multi.new("All the things: :current")
bars = Hash.new { |hash, key| hash[key] = main.register("#{key}: :current") }

5.times do |i|
  100.times do
    sleep 0.01
    bars["Thing #{i}"].advance
  end
end
```

### Actual behaviour
```
/Users/ttilberg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/tty-progressbar-0.18.1/lib/tty/progressbar/multi.rb:145:in `each': undefined method `+' for nil:NilClass (NoMethodError)
```

### Expected behaviour
```
▶ ruby multi.rb
┌ Total: 500
└── Thing 0: 100
└── Thing 1: 100
└── Thing 2: 100
└── Thing 3: 100
└── Thing 4: 100
```

### Describe your environment

* OS version: `MacOS 10.15.7`
* Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`
* TTY::ProgressBar version: `0.18.1`

**Comment by piotrmurach** [comment]
Hi Tim 👋 

Thank you for using `tty-progressbar` and submitting this issue. 

The `indeterminate` progress is a new addition and despite my testing efforts, there are still some corner cases. So I'm glad you picked this one up and already provided PR!

**Comment by ttilberg** [comment]
PS: This came up while adding visual feedback to a [Kiba ETL](https://github.com/thbar/kiba) pipeline for archiving a large BI database. It powers the following cool visual. I was so delighted by how well and clever it all worked -- thanks for TTY Toolkit!

```rb
# ...
        progress = TTY::ProgressBar::Multi.new("[time: :elapsed] :current records @ :rate rec/sec",
          hide_cursor: true,
          frequency: 5
        )
        progress_for = Hash.new { |hash, key| hash[key] = progress.register(" > #{key} [time: :elapsed] :current records") }

        transform do |row|
          progress_for[row[:_filename]].advance

          row
        end
# ...
```

<img width="923" alt="image" src="https://user-images.githubusercontent.com/7969650/107860831-5b44e400-6e07-11eb-90c8-b41adae8b176.png">

**Comment by piotrmurach** [comment]
Thank you for sharing! That's quite a few records to shift around you got there. I like to see how TTY gems are used and how they plug into different workflows.
